// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TripLog.Models;

#nullable disable

namespace TripLog.Migrations
{
    [DbContext(typeof(TripContext))]
    [Migration("20240310194401_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TripLog.Models.Trip", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Accomodation")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("EndDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("StartDate")
                        .IsRequired()
                        .HasColumnType("datetime2");

                    b.Property<string>("Thingstodo1")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Thingstodo2")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Thingstodo3")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Trips", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Accomodation = "The Benson Hotel",
                            Destination = "Portland",
                            Email = "staff@thebenson.com",
                            EndDate = new DateTime(2024, 3, 10, 15, 44, 0, 737, DateTimeKind.Local).AddTicks(2847),
                            Phone = "503-555-1234",
                            StartDate = new DateTime(2024, 3, 10, 15, 44, 0, 737, DateTimeKind.Local).AddTicks(2794),
                            Thingstodo1 = "Get Voodoo donuts",
                            Thingstodo2 = "Walk in the rain",
                            Thingstodo3 = "Go to Powell's"
                        },
                        new
                        {
                            Id = 2,
                            Accomodation = "Holiday Inn Express",
                            Destination = "Boise",
                            EndDate = new DateTime(2024, 3, 10, 15, 44, 0, 737, DateTimeKind.Local).AddTicks(2852),
                            StartDate = new DateTime(2024, 3, 10, 15, 44, 0, 737, DateTimeKind.Local).AddTicks(2850),
                            Thingstodo1 = "Visit Family"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
